### ISSUE TITLE
Error installing for first time

### ISSUE THREAD

**Issue by GioacchinoMendola** [alejandrososa/Yii-PowerPoint-Component#1]
[RuntimeException]
  Could not delete /apps/html/MYAPP/vendor/phpoffice/phppresentation/.git/objects/pack/tmp_pack_KphmpZ:

**Comment by alejandrososa** [comment]
Es preferible ejecutar en la medida de lo posible el comando composer con un usuario normal de linux y no con root para no tener problemas de permisos al tratar de eliminar algo.
